version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - realtime_pipeline

  kafka:
    image: 'bitnami/kafka:latest'
    user: root
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - realtime_pipeline
    depends_on:
      - zookeeper

  spark:
    image: jupyter/all-spark-notebook:latest  # Utilisez l'image appropriée pour PySpark
    ports:
      - "8088:8888"
      - "4040:4040"
    volumes:
      - "C:/Users/Youcode/kafka_project:/home/jovyan/work"
    networks:
      - realtime_pipeline

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    networks:
      - realtime_pipeline

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - realtime_pipeline

networks:
  realtime_pipeline:
